- name: Setup nginx and deploy hello world
  hosts: webservers
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
        update_cache: yes
    - name: Start nginx
      systemd:
        name: nginx
        state: started
        enabled: true
    - name: Deploy Hello World page
      copy:
        content: |
          <html>
          <head>
          <title>Hello World</title>
          </head>
          <body>
          <h1>Hellow World!</h1>
          </body>
          </html>
      dest: /usr/share/nginx/html/index.html
